/**
 * buildScoreRow — the pure mapping from a scored session to the anonymous
 * "Store A" row (spec §14.1). This is the one place an `AssessmentResult` becomes
 * the no-PII record that lands in `public.scores`.
 *
 * Three guarantees, by construction:
 *   1. NO PII can ever be present. The row shape is derived from `scoreRowSchema`
 *      (a strict Zod object), so the `ScoreRow` type has EXACTLY the allowed keys
 *      — adding `email`/`phone`/`parentFirstName`/a lead id is a compile error
 *      here and a validation error at `/api/score`.
 *   2. NO timestamp and NO lead key. There is no `created_at` and no `id` field —
 *      the date is stamped DATE-ONLY by the database default; the surrogate `id`
 *      is generated by the database and is never shared with the lead store.
 *   3. Pure: no clock, no randomness, no env. Version stamps come from
 *      `result.meta`; demographics are passed in. Same input ⇒ deep-equal row.
 *
 * The client builds the row and POSTs it to `/api/score`; the server re-validates
 * with the SAME `scoreRowSchema`, stamps `environment`, and inserts. `environment`
 * and `created_date` are intentionally NOT part of this row — they are stamped
 * server-side / by the DB so the client can never influence them.
 */

import { z } from "zod";

import { GENDER_VALUES } from "@/features/lead/schema";
import type { IndexKey } from "@/lib/indices";
import type { ScoredSignal } from "@/content/norms";
import type { AssessmentResult } from "../types";
import type { Confidence, SessionValidity } from "../types";

/**
 * The 8 fine signals, in spec order (§3.1). `satisfies` rejects a typo'd key at
 * compile time; the runtime test asserts the set is exactly `ScoredSignal`.
 */
export const SIGNAL_KEYS = [
  "gf",
  "gv",
  "gsm",
  "gs",
  "attention",
  "ef",
  "glr",
  "ct",
] as const satisfies readonly ScoredSignal[];

/**
 * The single, tested IndexKey → DB-column mapping. The app's `IndexKey` is terse
 * (`memory`, `planning`, `stem`); the columns are self-documenting for whoever
 * queries the table in raw SQL. `satisfies Record<IndexKey, string>` forces every
 * index to be mapped; a test ties each value to the right column.
 */
export const INDEX_COLUMN = {
  logic: "logic",
  spatial: "spatial",
  memory: "memory_focus",
  planning: "planning_speed",
  stem: "learning_stem",
} as const satisfies Record<IndexKey, string>;

/** Confidence labels, tied to the live `Confidence` type (catches drift like "med"). */
const CONFIDENCE_VALUES = [
  "high",
  "medium",
  "low",
] as const satisfies readonly Confidence[];

/** Validity verdicts, tied to the live `SessionValidity` type ("ok", not "none"). */
const VALIDITY_VALUES = [
  "ok",
  "mild",
  "strong",
] as const satisfies readonly SessionValidity[];

const NORMS_STAGE_VALUES = ["seed", "real"] as const;

const indexScore = () => z.number().int().min(0).max(100);
const signalScore = () => z.number().int().min(0).max(100);
const confidence = () => z.enum(CONFIDENCE_VALUES);

/**
 * The anonymous score row — the SINGLE source of the row's shape, used to build
 * it (client) and to validate it (server). `.strict()` rejects ANY unknown key,
 * so PII (`email`, `phone`, `parentFirstName`), a lead id, or a client-supplied
 * `created_date` / `created_at` / `environment` are all rejected, not silently
 * dropped. Mirrors the DB column types + CHECK constraints in the migration.
 */
export const scoreRowSchema = z
  .object({
    // demographics (coarse — not identifying; spec §14.1)
    age: z.number().int().min(5).max(13),
    child_gender: z.enum(GENDER_VALUES).nullable(),
    city: z.string().trim().min(1).max(80),
    language: z.string().trim().min(1).max(16),

    // 8 fine signals (0–100)
    gf: signalScore(),
    gv: signalScore(),
    gsm: signalScore(),
    gs: signalScore(),
    attention: signalScore(),
    ef: signalScore(),
    glr: signalScore(),
    ct: signalScore(),

    // 5 parent-facing composite indices (0–100)
    logic: indexScore(),
    spatial: indexScore(),
    memory_focus: indexScore(),
    planning_speed: indexScore(),
    learning_stem: indexScore(),

    // 5 per-index confidence labels (spec §6.5)
    conf_logic: confidence(),
    conf_spatial: confidence(),
    conf_memory_focus: confidence(),
    conf_planning_speed: confidence(),
    conf_learning_stem: confidence(),

    // validity verdict (spec §7.1)
    validity_status: z.enum(VALIDITY_VALUES),

    // version stamps (spec §19.3–19.4 / §6.6)
    task_bank_version: z.string().min(1),
    scoring_version: z.string().min(1),
    norms_version: z.string().min(1),
    norms_stage: z.enum(NORMS_STAGE_VALUES),
  })
  .strict();

/** The validated anonymous row. Derived from the schema → exactly the allowed keys. */
export type ScoreRow = z.infer<typeof scoreRowSchema>;

/** The exact set of allowed row keys (anchors the no-PII / allowed-key-set tests). */
export const SCORE_ROW_KEYS = Object.keys(scoreRowSchema.shape) as Array<
  keyof ScoreRow
>;

/** Form-collected demographics for the row. NO PII — age comes from `result.meta`. */
export interface ScoreDemographics {
  city: string;
  /** Optional; absent ⇒ stored as NULL. */
  childGender?: (typeof GENDER_VALUES)[number];
  /** UI language at assessment time (MVP: "mk"). */
  language: string;
}

/**
 * Map a scored session + form demographics → the anonymous row. The literal below
 * is the single construction site; its index columns follow `INDEX_COLUMN` (tied
 * by a test). The return type is `ScoreRow`, so it is impossible to add a key the
 * schema does not allow — PII, a lead id, or a timestamp will not compile.
 */
export function buildScoreRow(
  result: AssessmentResult,
  demographics: ScoreDemographics,
): ScoreRow {
  const { signals, indices, meta, validity } = result;
  return {
    // Age is authoritative in result.meta (what scoring used) — not re-passed.
    age: meta.age,
    child_gender: demographics.childGender ?? null,
    city: demographics.city,
    language: demographics.language,

    // 8 fine signals
    gf: signals.gf.index,
    gv: signals.gv.index,
    gsm: signals.gsm.index,
    gs: signals.gs.index,
    attention: signals.attention.index,
    ef: signals.ef.index,
    glr: signals.glr.index,
    ct: signals.ct.index,

    // 5 composite indices (IndexKey → column per INDEX_COLUMN)
    logic: indices.logic.value,
    spatial: indices.spatial.value,
    memory_focus: indices.memory.value,
    planning_speed: indices.planning.value,
    learning_stem: indices.stem.value,

    // 5 per-index confidence labels
    conf_logic: indices.logic.confidence,
    conf_spatial: indices.spatial.confidence,
    conf_memory_focus: indices.memory.confidence,
    conf_planning_speed: indices.planning.confidence,
    conf_learning_stem: indices.stem.confidence,

    // validity (spec §7.1)
    validity_status: validity.session,

    // version stamps (spec §19.3–19.4 / §6.6)
    task_bank_version: meta.taskBankVersion,
    scoring_version: meta.scoringVersion,
    norms_version: meta.normsVersion,
    norms_stage: meta.normsStage,
  };
}
